apiVersion: v1
kind: Service
metadata:
  name: content-web-service
  labels:
    app: content-web
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: kubernators
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: content-web
    version: "2"
