apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api-v1
  labels:
    app: content-api
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
      version: "1"
  template:
    metadata:
      labels:
        app: content-api
        version: "1"
    spec:
      containers:
      - name: content-api
        image: kubernators.azurecr.io/content-api:latest
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 250m
            memory: 128M
          limits:
            cpu: 250m
            memory: 128M
        livenessProbe:
          httpGet:
            path: /stats
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /stats
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 3
